export const CANVAS_AI_TEXT = {
  ru: {
    ai1Aria: "Решить на канвасе", ai1Title: "Решить на канвасе",
    ai2Aria: "Обсудить выделение", ai2Title: "Добавить задачу в чат",
    emptyChat: "Выделите задачу на листе или напишите её здесь. Решение появится на канвасе, а пояснения — в чате.",
    thinking: "Разбираю задачу и ищу место…", writing: "Пишу черновик на канвасе…",
    draftTitle: "Черновик решения", draftHint: "Проверьте решение. Можно попросить исправление в чате.",
    acceptDraft: "Принять", discardDraft: "Убрать", stopAi: "Остановить",
    accepted: "Решение принято и добавлено на канвас.", discarded: "Черновик убран.",
    aiRequestFailed: "Не удалось подготовить решение. Повторите запрос; предыдущий черновик сохранён, если он был.",
    formulaFailed: "Не удалось отобразить формулы. Повторите запрос.",
    formulaTooLarge: "Формула слишком большая для листа. Попросите ИИ разбить её на более короткие шаги.",
    chatFailed: "Не удалось сохранить сообщение. Повторите отправку.",
    draftPage: "Черновик · лист", revisePlaceholder: "Что исправить или объяснить?",
    reviewBeforeLeaving: "Примите или уберите черновик, чтобы выйти",
    acceptedSaveFailed: "Решение добавлено, но сохранить его не удалось. Повторите сохранение.",
    retrySave: "Повторить сохранение",
  },
  en: {
    ai1Aria: "Solve on canvas", ai1Title: "Solve on canvas",
    ai2Aria: "Discuss selection", ai2Title: "Add task to chat",
    emptyChat: "Select a problem on the page or type it here. The solution appears on the canvas, with explanations in chat.",
    thinking: "Reading the problem and finding space…", writing: "Writing a draft on the canvas…",
    draftTitle: "Solution draft", draftHint: "Review the solution. Ask for changes in chat if needed.",
    acceptDraft: "Accept", discardDraft: "Discard", stopAi: "Stop",
    accepted: "Solution accepted and added to the canvas.", discarded: "Draft discarded.",
    aiRequestFailed: "Could not prepare a solution. Try again; any previous draft has been kept.",
    formulaFailed: "Could not render the formulas. Please try again.",
    formulaTooLarge: "A formula is too large for the page. Ask AI to split it into shorter steps.",
    chatFailed: "Could not save the message. Please send it again.",
    draftPage: "Draft · page", revisePlaceholder: "What should I change or explain?",
    reviewBeforeLeaving: "Accept or discard the draft before leaving",
    acceptedSaveFailed: "The solution was added but could not be saved. Please retry saving.",
    retrySave: "Retry saving",
  },
  zh: {
    ai1Aria: "在画布上解题", ai1Title: "在画布上解题",
    ai2Aria: "讨论所选内容", ai2Title: "将题目添加到聊天",
    emptyChat: "选择画布上的题目，或在这里输入。解答将写在画布上，简短说明显示在聊天中。",
    thinking: "正在理解题目并寻找空白区域…", writing: "正在画布上书写草稿…",
    draftTitle: "解答草稿", draftHint: "请检查解答。您可以在聊天中要求修改。",
    acceptDraft: "接受", discardDraft: "移除", stopAi: "停止",
    accepted: "解答已接受并添加到画布。", discarded: "草稿已移除。",
    aiRequestFailed: "无法生成解答，请重试。原有草稿已保留。",
    formulaFailed: "无法显示公式，请重试。",
    formulaTooLarge: "公式过大，无法放入页面。请要求 AI 将其拆分为更短的步骤。",
    chatFailed: "无法保存消息，请重新发送。",
    draftPage: "草稿 · 页", revisePlaceholder: "需要修改或解释什么？",
    reviewBeforeLeaving: "请先接受或移除草稿再退出",
    acceptedSaveFailed: "解答已添加，但保存失败，请重试保存。",
    retrySave: "重新保存",
  },
};
