async page => {
  const assert = (ok, label) => { if (!ok) throw new Error(label); };
  const passed = [];
  const idA='a'.repeat(64), idB='b'.repeat(64);
  const image='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="20" height="30"><path d="M3 27L10 3L17 27" fill="none" stroke="black" stroke-width="3"/></svg>');
  const glyphs=['x','y','1','2','3','6','+','-','=','dx','dy','\\sin','\\cos'].map(latex=>({latex,medoidId:'A-'+latex,image,width:20,height:30}));
  const catalog=[idA,idB].map((id,i)=>({id,name:i?'Dataset B':'Dataset A',updatedAt:'2026-09-10T00:00:00Z',createdAt:'2026-09-10T00:00:00Z',sourceVersion:1,status:'approved',analysisStatus:'complete',total:39,pending:0,accepted:39,rejected:0,exportable:39}));
  let loads=0, holdB=false, failB=false, approveB=true, releaseB;
  await page.route('**/dev/datasets',route=>route.fulfill({json:catalog}));
  await page.route('**/dev/datasets/*/writing',async route=>{
    const second=route.request().url().includes(idB); loads++;
    if(second&&holdB) await new Promise(resolve=>{releaseB=resolve;});
    if(second&&failB) return route.fulfill({status:503,json:{error:'Synthetic loading failure'}});
    await route.fulfill({json:{id:second?idB:idA,name:second?'Dataset B':'Dataset A',approved:second?approveB:true,status:'complete',sourceVersion:1,computedAt:'2026-09-10T00:00:00Z',glyphs:second?glyphs.map(g=>({...g,medoidId:'B-'+g.latex})):glyphs}}).catch(()=>{});
  });
  await page.setViewportSize({width:1280,height:900});
  await page.reload();
  await page.waitForFunction(()=>document.querySelector('#audit')?.textContent.includes('"failures":[]'));
  await page.locator('#checks, #audit').evaluateAll(nodes=>nodes.forEach(node=>node.style.display='none'));
  const upper=page.getByRole('region',{name:'LaTeX preview',exact:true});
  const lower=page.getByRole('region',{name:'Handwriting result',exact:true});
  const source=page.getByRole('textbox',{name:'LaTeX input'});
  const download=page.getByRole('button',{name:'Download PNG'});
  const ready=()=>page.waitForFunction(()=>document.querySelector('[aria-label="Handwriting result"] [aria-busy]')?.getAttribute('aria-busy')==='false'&&!!document.querySelector('[aria-label="Handwriting result"] img'));
  const svg=()=>lower.getByRole('img').getAttribute('src').then(src=>decodeURIComponent(src.split(',').slice(1).join(',')));
  const setSource=async value=>{await source.fill(value);await ready();};
  await ready();
  await setSource('\\frac{dx}{dy}=x^2+\\sin x');
  await upper.getByRole('checkbox',{name:'Boxes',exact:true}).check();
  await lower.getByRole('checkbox',{name:'Boxes',exact:true}).check();
  const cells=async region=>region.locator('[class*="cellOutline"]').evaluateAll(nodes=>nodes.map(n=>['x','y','width','height'].map(a=>Number(n.getAttribute(a)))));
  const handCells=await cells(lower);
  await lower.getByRole('checkbox',{name:'Printed',exact:true}).check();await ready();
  const printedCells=await cells(lower), upperCells=await cells(upper);
  assert(handCells.length===printedCells.length&&upperCells.length===handCells.length,'Same unit counts in all modes');
  handCells.forEach((cell,i)=>cell.forEach((n,j)=>assert(Math.abs(n-printedCells[i][j])<.004&&Math.abs(n-upperCells[i][j])<.004,'Cell remains identical')));
  await lower.getByRole('group',{name:'Symbol boxes'}).getByRole('button').first().focus();
  await page.keyboard.press('Enter');
  assert(await lower.locator('[aria-label="Selected symbol"]').count()===1,'Keyboard selection opens inspector');
  assert((await lower.locator('[aria-label="Selected symbol"]').textContent()).includes('Printed'),'Inspector reports printed source');
  passed.push('same Cell in three previews; grouping; keyboard inspector');
  const zero=await svg();
  await page.getByRole('slider',{name:'Variation',exact:true}).focus();await page.keyboard.press('End');await ready();
  assert(await svg()!==zero,'Printed variation changes output');
  await page.keyboard.press('Home');await ready();
  await page.locator('summary').filter({hasText:/^Spacing$/}).click();
  await page.getByRole('slider',{name:'Padding all'}).focus();await page.keyboard.press('End');await ready();
  assert(await svg()!==zero,'Printed padding changes output');
  await page.keyboard.press('Home');await ready();
  passed.push('printed Padding and Variation are effective');
  await lower.getByRole('checkbox',{name:'Printed',exact:true}).uncheck();await ready();
  await setSource('x+q');
  assert((await svg()).includes('data-font-fallback'),'Missing glyph uses visible fallback setting');
  await page.getByRole('combobox',{name:'Missing symbol display'}).selectOption('placeholder');await ready();
  assert((await svg()).includes('data-missing="q"'),'Explicit placeholder mode');
  await page.getByRole('combobox',{name:'LaTeX presets'}).selectOption({label:'Exercise 7 · Triple integral'});await ready();
  assert(await page.getByRole('combobox',{name:'Missing symbol display'}).inputValue()==='placeholder','Preset does not secretly change fallback');
  await page.getByRole('combobox',{name:'Missing symbol display'}).selectOption('printed');await ready();
  for(const name of ['Exercise 7 · Triple integral','Exercise 8 · Variable limits','Exercise 9 · Logarithmic integral','Exercise 2.1-2 · Probability mass function']){
    await page.getByRole('combobox',{name:'LaTeX presets'}).selectOption({label:name});await ready();
    assert(!(await svg()).includes('data-missing='),'Full worked solution stays readable');
  }
  passed.push('explicit missing glyph mode; all four full solutions; no hidden preset behavior');
  await setSource('x+1');
  await lower.getByRole('checkbox',{name:'Printed',exact:true}).check();await ready();
  await page.getByRole('button',{name:'Text',exact:true}).click();
  assert(await page.getByRole('textbox',{name:'Text input'}).inputValue()==='','Text has independent input');
  await page.getByRole('textbox',{name:'Text input'}).fill('x?\nxx');await ready();
  assert((await svg()).includes('data-missing="?"'),'Text missing glyph remains visible after Printed');
  assert(await page.getByText('Missing symbols',{exact:true}).count()===1,'Text missing list is not hidden');
  await page.getByRole('button',{name:'LaTeX',exact:true}).click();await ready();
  assert(await source.inputValue()==='x+1','LaTeX input restored');
  passed.push('Text and LaTeX inputs/settings do not leak');
  await source.fill('\\frac{');
  assert(await download.isDisabled(),'Old export disabled immediately after input change');
  await page.getByRole('alert').filter({hasText:'Invalid LaTeX'}).waitFor();
  assert(await lower.getByRole('img').count()===0,'Invalid input clears old result');
  await source.fill('');assert(await download.isDisabled(),'Empty input cannot export');
  await setSource('x+1');
  const initialLoads=loads;
  const refreshed=page.waitForResponse(r=>r.url().endsWith('/dev/datasets'));
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await refreshed;
  assert(loads===initialLoads,'Unchanged catalog does not reload selected dataset');
  holdB=true;
  await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption(idB);
  assert(await download.isDisabled(),'Dataset switch cannot export stale symbols');
  await page.waitForFunction(()=>document.querySelector('[aria-label="Handwriting result"] [aria-busy]')?.getAttribute('aria-busy')==='true');
  await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption(idA);await ready();
  holdB=false;if(releaseB)releaseB();
  await lower.getByRole('checkbox',{name:'Printed',exact:true}).uncheck();await ready();
  assert((await svg()).includes('data-medoid="A-x"')&&!(await svg()).includes('data-medoid="B-'),'Late dataset response cannot replace selection');
  failB=true;await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption(idB);
  await page.getByRole('alert').filter({hasText:'Synthetic loading failure'}).waitFor();
  assert(await download.isDisabled(),'Failed dataset cannot export old result');
  failB=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await ready();
  assert((await svg()).includes('data-medoid="B-x"'),'Retry loads selected dataset');
  passed.push('stale export protection; empty/invalid input; focus refresh; request race; retry');
  await setSource('\\frac{x^2+1}{y}');
  await lower.getByRole('checkbox',{name:'Reference bounds'}).check();
  const exported=page.waitForEvent('download');await download.click();const file=await exported;
  await file.saveAs('output/playwright/writing-audit-export.png');
  assert(!(await svg()).includes('boxOverlay'),'Export source contains no diagnostic overlays');
  await upper.scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/writing-audit-desktop.png'});
  await page.setViewportSize({width:390,height:844});await ready();
  await lower.scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/writing-audit-mobile.png'});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile page overflow');
  await setSource('-');await lower.getByRole('checkbox',{name:'Printed',exact:true}).check();await ready();
  await lower.scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/writing-audit-minus-boxes.png'});
  passed.push('PNG export with overlays enabled; mobile layout; thin minus inspection');
  await lower.getByRole('checkbox',{name:'Printed',exact:true}).uncheck();await ready();
  approveB=false;
  await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption(idA);await ready();
  await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption(idB);
  await page.getByText('Dataset needs approval.',{exact:true}).waitFor();
  assert(await download.isDisabled()&&await lower.getByRole('img').count()===0,'Unapproved samples cannot masquerade as ready handwriting');
  const audit=JSON.parse(await page.locator('#audit').textContent());
  await page.route('**/dev/datasets',route=>route.fulfill({json:[]}));
  await page.reload();
  await page.getByRole('option',{name:'No datasets',exact:true}).waitFor({state:'attached'});
  await lower.getByRole('checkbox',{name:'Printed',exact:true}).check();await ready();
  assert(await download.isEnabled(),'Printed output works with an empty catalog');
  passed.push('unapproved dataset blocked; printed output without a dataset');
  return {passed,requests:loads,audit};
}
